/*[
  {
    "name": "BottomNavigationBar",
    "description": "A fixed navigation bar at the bottom of the screen with four labeled icons: 'Home', 'My Cards', 'Statistics', and 'Settings'. Found on Home, My Cards, Statistics, Settings, and Transaction History screens.",
    "standardization": "Accepts an array of navigation items (icon, label), current active tab, and onTabSelect handler as parameters.",
    "styling_changes": "Slight background color shade variation and icon highlight state for the active tab.",
    "code": "// lib/features/account_statistics/widgets/bottom_navigation_bar.dart\nimport 'package:flutter/material.dart';\nimport 'package:banking_app_hutouch_ai/core/constants/color_config.dart';\nimport 'package:banking_app_hutouch_ai/features/account_statistics/widgets/bottom_nav_item.dart';\n\nclass BottomNavigationBar extends StatelessWidget {\n  final int currentIndex;\n  final ValueChanged<int>? onTabSelect;\n  const BottomNavigationBar({super.key, this.currentIndex = 0, this.onTabSelect});\n\n  static const items = [\n    {'icon': Icons.home, 'labelKey': 'home'},\n    {'icon': Icons.credit_card, 'labelKey': 'my_cards'},\n    {'icon': Icons.bar_chart, 'labelKey': 'statistics_nav'},\n    {'icon': Icons.settings, 'labelKey': 'settings'},\n  ];\n\n  @override\n  Widget build(BuildContext context) {\n    final height = MediaQuery.of(context).size.height;\n    return Container(\n      height: height * 0.09,\n      decoration: BoxDecoration(\n        color: Theme.of(context).colorScheme.surface.withOpacity(0.95),\n        border: Border(top: BorderSide(color: kOutlineColor.withOpacity(0.15), width: 1)),\n      ),\n      child: Row(\n        mainAxisAlignment: MainAxisAlignment.spaceAround,\n        children: List.generate(items.length, (index) {\n          final map = items[index];\n          return BottomNavItem(\n            icon: map['icon'] as IconData,\n            labelKey: map['labelKey'] as String,\n            isActive: index == currentIndex,\n            onTap: () => onTabSelect?.call(index),\n          );\n        }),\n      ),\n    );\n  }\n}\n"
  },
  {
    "name": "TransactionListItem",
    "description": "A list row showing a transaction with an icon, merchant name (e.g. 'Apple Store', 'Spotify', 'Money Transfer', 'Grocery', 'Netflix'), sublabel (e.g. 'Entertainment', 'Music', 'Transaction', 'Shopping'), and amount (e.g. '- $5,99', '$300'). Found on Home, My Cards, Statistics, Search, and Transaction History screens.",
    "standardization": "Accepts parameters for icon, merchant name, sublabel, amount, amount color (normal or highlight), and optional click handler.",
    "styling_changes": "Minor adjustment in divider margin depending on list density.",
    "code": "// lib/features/account_statistics/widgets/transaction_list_item.dart\nimport 'package:flutter/material.dart';\nimport 'package:get/get.dart';\nimport 'package:banking_app_hutouch_ai/core/constants/text_style.dart';\n\nclass TransactionListItem extends StatelessWidget {\n  final Widget icon;\n  final String merchantName;\n  final String subLabel;\n  final String amount;\n  final Color amountColor;\n  final VoidCallback? onTap;\n  final bool dense;\n  const TransactionListItem({\n    super.key,\n    required this.icon,\n    required this.merchantName,\n    required this.subLabel,\n    required this.amount,\n    required this.amountColor,\n    this.onTap,\n    this.dense = false,\n  });\n\n  @override\n  Widget build(BuildContext context) {\n    return Column(\n      children: [\n        Padding(\n          padding: EdgeInsets.symmetric(vertical: dense ? 4 : 8, horizontal: 0),\n          child: InkWell(\n            onTap: onTap,\n            child: Row(\n              children: [\n                SizedBox(width: 48, height: 48, child: icon),\n                const SizedBox(width: 12),\n                Expanded(\n                  child: Column(\n                    crossAxisAlignment: CrossAxisAlignment.start,\n                    children: [\n                      Text(\n                        merchantName.tr,\n                        style: AppTextStyles.transactionTitle,\n                      ),\n                      Text(\n                        subLabel.tr,\n                        style: AppTextStyles.transactionSubtitle,\n                      ),\n                    ],\n                  ),\n                ),\n                Text(\n                  amount,\n                  style: AppTextStyles.transactionTitle.copyWith(color: amountColor),\n                )\n              ],\n            ),\n          ),\n        ),\n        Container(\n          margin: EdgeInsets.only(\n            left: 60,\n            right: 0,\n            top: dense ? 6 : 10,\n            bottom: 0,\n          ),\n          height: 1,\n          color: Colors.grey.withOpacity(0.09),\n        ),\n      ],\n    );\n  }\n}\n"
  },
  {
    "name": "PrimaryActionButton",
    "description": "A prominent rounded blue button used for main actions labeled 'Sign In', 'Sign Up', 'Change Password', 'Send Money', 'Add Card', and 'Next'. Found on Sign In, Sign Up, Change Password, Request Money, Send Money, Add Card, and onboarding screens.",
    "standardization": "Accepts parameters for button label text, optional icon, onPress handler, and disabled/loading state.",
    "styling_changes": "Button width may stretch to fit parent and slight vertical margin adjustments per screen type.",
    "code": "// lib/features/account_statistics/widgets/primary_action_button.dart\nimport 'package:flutter/material.dart';\nimport 'package:banking_app_hutouch_ai/core/constants/color_config.dart';\n\nclass PrimaryActionButton extends StatelessWidget {\n  final String label;\n  final VoidCallback? onPressed;\n  final bool loading;\n  final bool disabled;\n  final IconData? icon;\n  const PrimaryActionButton({\n    super.key,\n    required this.label,\n    this.onPressed,\n    this.loading = false,\n    this.disabled = false,\n    this.icon,\n  });\n\n  @override\n  Widget build(BuildContext context) {\n    final width = MediaQuery.of(context).size.width;\n    return SizedBox(\n      width: width,\n      child: ElevatedButton.icon(\n        icon: icon == null\n            ? const SizedBox.shrink()\n            : Icon(icon, color: Colors.white),\n        label: loading\n            ? const CircularProgressIndicator(color: Colors.white)\n            : Text(label),\n        style: ElevatedButton.styleFrom(\n          backgroundColor: kPrimaryColor,\n          minimumSize: const Size.fromHeight(48),\n          shape:\n              RoundedRectangleBorder(borderRadius: BorderRadius.circular(32)),\n          elevation: 0,\n        ),\n        onPressed: disabled || loading ? null : onPressed,\n      ),\n    );\n  }\n}\n"
  },
  {
    "name": "InputField",
    "description": "A text input field, optionally with a left icon, label, and optional right icon (e.g., eye for password visibility). Found on Sign In (Email Address, Password), Sign Up (Full Name, Phone Number, Email Address, Password), Change Password (Current Password, New Password, Confirm New Password), Request Money, Add New Card, Edit Profile.",
    "standardization": "Accepts parameters for label, value, placeholder, left icon, right icon with handler, input type, and onChange event.",
    "styling_changes": "Minor width adjustments. Padding and line color are consistent.",
    "code": "// lib/features/account_statistics/widgets/input_field.dart\nimport 'package:flutter/material.dart';\n\nclass InputField extends StatelessWidget {\n  final String label;\n  final String value;\n  final String placeholder;\n  final IconData? leftIcon;\n  final IconData? rightIcon;\n  final VoidCallback? onRightIconTap;\n  final TextInputType inputType;\n  final ValueChanged<String>? onChanged;\n  const InputField({\n    super.key,\n    required this.label,\n    required this.value,\n    required this.placeholder,\n    this.leftIcon,\n    this.rightIcon,\n    this.onRightIconTap,\n    this.inputType = TextInputType.text,\n    this.onChanged,\n  });\n  @override\n  Widget build(BuildContext context) {\n    return TextField(\n      controller: TextEditingController(text: value),\n      decoration: InputDecoration(\n        labelText: label,\n        hintText: placeholder,\n        prefixIcon: leftIcon == null ? null : Icon(leftIcon),\n        suffixIcon: rightIcon == null\n            ? null\n            : GestureDetector(onTap: onRightIconTap, child: Icon(rightIcon)),\n        border: const OutlineInputBorder(),\n        contentPadding: const EdgeInsets.symmetric(horizontal: 16),\n      ),\n      keyboardType: inputType,\n      onChanged: onChanged,\n    );\n  }\n}\n"
  },
  {
    "name": "ScreenHeader",
    "description": "A standardized top bar with a centered title and left arrow for navigation. Sometimes with a right icon/button (e.g., profile, close, notification, add card). Found on Profile, Statistics, My Cards, Settings, Search, All Cards, Add New Card, Request Money, Send Money, Transaction History, Edit Profile, Language, Terms & Condition.",
    "standardization": "Accepts parameters for title text, optional left action/icon, and optional right action/icon.",
    "styling_changes": "Rare right icon change. Consistent height, background, and font size.",
    "code": "// lib/features/account_statistics/widgets/screen_header.dart\nimport 'package:flutter/material.dart';\nimport 'package:get/get.dart';\nimport 'package:banking_app_hutouch_ai/core/constants/text_style.dart';\nimport 'package:banking_app_hutouch_ai/core/constants/color_config.dart';\n\nclass ScreenHeader extends StatelessWidget {\n  final String title;\n  final IconData? leftIcon;\n  final IconData? rightIcon;\n  final VoidCallback? onLeftPressed;\n  final VoidCallback? onRightPressed;\n  const ScreenHeader({\n    super.key,\n    required this.title,\n    this.leftIcon,\n    this.rightIcon,\n    this.onLeftPressed,\n    this.onRightPressed,\n  });\n\n  @override\n  Widget build(BuildContext context) {\n    final size = MediaQuery.of(context).size;\n    return Material(\n      color: Theme.of(context).colorScheme.background,\n      child: Container(\n        height: size.height * 0.09,\n        padding: EdgeInsets.symmetric(\n          horizontal: size.width * 0.05,\n        ),\n        alignment: Alignment.bottomCenter,\n        child: Row(\n          children: [\n            if (leftIcon != null)\n              InkWell(\n                borderRadius: BorderRadius.circular(30),\n                onTap: onLeftPressed ?? () => Get.back(),\n                child: Container(\n                  width: 40,\n                  height: 40,\n                  decoration: BoxDecoration(\n                    shape: BoxShape.circle,\n                    color: Theme.of(context).colorScheme.surface,\n                    border: Border.all(color: kOutlineColor, width: 1),\n                  ),\n                  child: Icon(leftIcon, color: kOnSurfaceColor),\n                ),\n              ),\n            Expanded(\n              child: Center(\n                child: Text(\n                  title.tr,\n                  style: AppTextStyles.title,\n                  textAlign: TextAlign.center,\n                ),\n              ),\n            ),\n            if (rightIcon != null)\n              InkWell(\n                borderRadius: BorderRadius.circular(30),\n                onTap: onRightPressed,\n                child: Container(\n                  width: 40,\n                  height: 40,\n                  decoration: BoxDecoration(\n                    shape: BoxShape.circle,\n                    color: Theme.of(context).colorScheme.surface,\n                    border: Border.all(color: kOutlineColor, width: 1),\n                  ),\n                  child: Icon(rightIcon, color: kOnSurfaceColor),\n                ),\n              ),\n          ],\n        ),\n      ),\n    );\n  }\n}\n"
  }
]*/